title: ImportLogs
modelClass: CanThis\ImportExport\Models\ProductsImport
list: $/canthis/importexport/models/productsimport/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '10'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
