plugin:
    name: 'canthis.importexport::lang.plugin.name'
    description: 'canthis.importexport::lang.plugin.description'
    author: CanThis
    icon: oc-icon-upload
    homepage: ''
navigation:
    importexport:
        label: 'Chunk Import Test'
        url: canthis/importexport/products/
        icon: icon-upload
        sideMenu:
            products:
                label: Products
                url: canthis/importexport/products/
                icon: icon-cubes
            import-log:
                label: 'Import Log'
                url: canthis/importexport/importlogs/
                icon: icon-history
